name = "Example"
uuid = "f67a1976-13ed-4d79-b3a8-d573f215c6cf"
authors = ["Noah Rhodes"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
